// ============================================================
// Auto-generated by GoogleSheetCodeGenerator.
// Do NOT edit manually — 컬럼 구조 변경 시 툴을 재실행하세요.
// ============================================================
using System;
using Cysharp.Threading.Tasks;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Networking;

/// <summary>
/// Google Sheets JSON API를 런타임에 직접 호출하여 MetaData를 파싱합니다.
/// 빌드 후에도 시트 데이터 변경이 즉시 반영됩니다 (재빌드 불필요).
/// </summary>
public class SpecDataManager
{
    public bool IsReady { get; private set; }

    Dictionary<int, ItemMetaData> _itemDict = new Dictionary<int, ItemMetaData>();
    List<ItemMetaData>            _itemList = new List<ItemMetaData>();
    Dictionary<int, AttendanceMetaData> _attendanceDict = new Dictionary<int, AttendanceMetaData>();
    List<AttendanceMetaData>            _attendanceList = new List<AttendanceMetaData>();
    Dictionary<int, AttendanceRewardMetaData> _attendanceRewardDict = new Dictionary<int, AttendanceRewardMetaData>();
    List<AttendanceRewardMetaData>            _attendanceRewardList = new List<AttendanceRewardMetaData>();

    public async UniTask DownloadDataSheetAsync()
    {
        IsReady = false;
        Debug.Log("[SpecDataManager] 데이터 다운로드 시작");

        await FetchItemAsync();
        await FetchAttendanceAsync();
        await FetchAttendanceRewardAsync();

        IsReady = true;
        Debug.Log("[SpecDataManager] 모든 데이터 로드 완료");
    }

    async UniTask FetchItemAsync()
    {
        string url = GoogleSheetConfig.BuildJsonUrl("Item");
        using (UnityWebRequest req = UnityWebRequest.Get(url))
        {
            await req.SendWebRequest().ToUniTask();
            if (req.result != UnityWebRequest.Result.Success)
            {
                Debug.LogError("[SpecDataManager] Item 다운로드 실패: " + req.error);
                return;
            }

            _itemDict.Clear();
            _itemList.Clear();

            List<string[]> rows = GvizParser.Parse(req.downloadHandler.text, colCount: 2);
            for (int i = 2; i < rows.Count; i++)
            {
                string[] cells = rows[i];
                if (string.IsNullOrEmpty(cells[0])) continue;
                try
                {
                    ItemMetaData data = new ItemMetaData
                    {
                        Id = ParseInt(cells[0]),
                        ItemType = ParseEnum<ItemType>(cells[1]),
                    };
                    _itemDict[data.Id] = data;
                    _itemList.Add(data);
                }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] Item 파싱 오류 row" + i + ": " + e.Message + " | " + string.Join(",", cells));
                }
            }

            Debug.Log("[SpecDataManager] Item 로드 완료: " + _itemList.Count + "개");
        }
    }

    async UniTask FetchAttendanceAsync()
    {
        string url = GoogleSheetConfig.BuildJsonUrl("Attendance");
        using (UnityWebRequest req = UnityWebRequest.Get(url))
        {
            await req.SendWebRequest().ToUniTask();
            if (req.result != UnityWebRequest.Result.Success)
            {
                Debug.LogError("[SpecDataManager] Attendance 다운로드 실패: " + req.error);
                return;
            }

            _attendanceDict.Clear();
            _attendanceList.Clear();

            List<string[]> rows = GvizParser.Parse(req.downloadHandler.text, colCount: 7);
            for (int i = 2; i < rows.Count; i++)
            {
                string[] cells = rows[i];
                if (string.IsNullOrEmpty(cells[0])) continue;
                try
                {
                    AttendanceMetaData data = new AttendanceMetaData
                    {
                        Id = ParseInt(cells[0]),
                        AttendanceSheetType = ParseEnum<AttendanceSheetType>(cells[1]),
                        AttendanceType = ParseEnum<AttendanceType>(cells[2]),
                        NameKey = cells[3],
                        TotalDays = ParseInt(cells[4]),
                        StartDateTime = ParseDateTime(cells[5]),
                        EndDateTime = ParseDateTime(cells[6]),
                    };
                    _attendanceDict[data.Id] = data;
                    _attendanceList.Add(data);
                }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] Attendance 파싱 오류 row" + i + ": " + e.Message + " | " + string.Join(",", cells));
                }
            }

            Debug.Log("[SpecDataManager] Attendance 로드 완료: " + _attendanceList.Count + "개");
        }
    }

    async UniTask FetchAttendanceRewardAsync()
    {
        string url = GoogleSheetConfig.BuildJsonUrl("AttendanceReward");
        using (UnityWebRequest req = UnityWebRequest.Get(url))
        {
            await req.SendWebRequest().ToUniTask();
            if (req.result != UnityWebRequest.Result.Success)
            {
                Debug.LogError("[SpecDataManager] AttendanceReward 다운로드 실패: " + req.error);
                return;
            }

            _attendanceRewardDict.Clear();
            _attendanceRewardList.Clear();

            List<string[]> rows = GvizParser.Parse(req.downloadHandler.text, colCount: 5);
            for (int i = 2; i < rows.Count; i++)
            {
                string[] cells = rows[i];
                if (string.IsNullOrEmpty(cells[0])) continue;
                try
                {
                    AttendanceRewardMetaData data = new AttendanceRewardMetaData
                    {
                        Id = ParseInt(cells[0]),
                        AttendanceSheetType = ParseEnum<AttendanceSheetType>(cells[1]),
                        Day = ParseInt(cells[2]),
                        RewardType = ParseEnum<ItemType>(cells[3]),
                        RewardCount = ParseInt(cells[4]),
                    };
                    _attendanceRewardDict[data.Id] = data;
                    _attendanceRewardList.Add(data);
                }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] AttendanceReward 파싱 오류 row" + i + ": " + e.Message + " | " + string.Join(",", cells));
                }
            }

            Debug.Log("[SpecDataManager] AttendanceReward 로드 완료: " + _attendanceRewardList.Count + "개");
        }
    }

    public ItemMetaData GetItem(int id)
    {
        ItemMetaData result;
        _itemDict.TryGetValue(id, out result);
        return result;
    }

    public ItemMetaData GetItem(ItemType key) => GetItem((int)key);

    public List<ItemMetaData> GetAllItem()
    {
        return _itemList;
    }

    public AttendanceMetaData GetAttendance(int id)
    {
        AttendanceMetaData result;
        _attendanceDict.TryGetValue(id, out result);
        return result;
    }

    public AttendanceMetaData GetAttendance(AttendanceSheetType key) => GetAttendance((int)key);

    public List<AttendanceMetaData> GetAllAttendance()
    {
        return _attendanceList;
    }

    public AttendanceRewardMetaData GetAttendanceReward(int id)
    {
        AttendanceRewardMetaData result;
        _attendanceRewardDict.TryGetValue(id, out result);
        return result;
    }

    public AttendanceRewardMetaData GetAttendanceReward(AttendanceSheetType key) => GetAttendanceReward((int)key);

    public List<AttendanceRewardMetaData> GetAllAttendanceReward()
    {
        return _attendanceRewardList;
    }

    static int ParseInt(string s)
    {
        if (string.IsNullOrEmpty(s)) return 0;
        if (s.Contains("."))
            return (int)float.Parse(s, System.Globalization.CultureInfo.InvariantCulture);
        return int.Parse(s);
    }
    static float ParseFloat(string s)
    {
        if (string.IsNullOrEmpty(s)) return 0f;
        return float.Parse(s, System.Globalization.CultureInfo.InvariantCulture);
    }
    static DateTime ParseDateTime(string s)
    {
        if (string.IsNullOrEmpty(s)) return default(DateTime);
        return DateTime.Parse(s, System.Globalization.CultureInfo.InvariantCulture);
    }
    static T ParseEnum<T>(string s) where T : struct
    {
        if (string.IsNullOrEmpty(s)) return default(T);
        return (T)Enum.Parse(typeof(T), s, true);
    }
    static List<T> ParseList<T>(string s, System.Func<string, T> parse)
    {
        var result = new List<T>();
        if (string.IsNullOrEmpty(s)) return result;
        string trimmed = s.Trim();
        if (trimmed.Length > 1 && trimmed[0] == '{' && trimmed[trimmed.Length - 1] == '}')
            trimmed = trimmed.Substring(1, trimmed.Length - 2);
        foreach (var part in trimmed.Split(','))
        {
            string t = part.Trim();
            if (!string.IsNullOrEmpty(t)) result.Add(parse(t));
        }
        return result;
    }
}
