// ============================================================
// Auto-generated by GoogleSheetCodeGenerator.
// Do NOT edit manually — 컬럼 구조 변경 시 툴을 재실행하세요.
// ============================================================
using System;
using System.Collections.Generic;

// 모든 MetaData 클래스는 이 파일에서 통합 관리합니다.
// 컬럼 구조가 바뀌면 에디터 툴을 재실행하세요.

// ── Item ─────────────────────────────────────────
[Serializable]
public class ItemMetaData
{
    public int Id;
    public ItemType ItemType;
}

// ── Attendance ─────────────────────────────────────────
[Serializable]
public class AttendanceMetaData
{
    public int Id;
    public AttendanceSheetType AttendanceSheetType;
    public AttendanceType AttendanceType;
    public string NameKey;
    public int TotalDays;
    public System.DateTime StartDateTime;
    public System.DateTime EndDateTime;
}

// ── AttendanceReward ─────────────────────────────────────────
[Serializable]
public class AttendanceRewardMetaData
{
    public int Id;
    public AttendanceSheetType AttendanceSheetType;
    public int Day;
    public ItemType RewardType;
    public int RewardCount;
}
