// ============================================================
// Auto-generated by GoogleSheetCodeGenerator.
// Do NOT edit manually — 컬럼 구조 변경 시 툴을 재실행하세요.
// ============================================================

public enum ItemType
{
    None = 0,
    GOLD,
    JEWEL,
    LEATHER,
    HELMET,
    SWORD,
    POTION,
}

public enum AttendanceSheetType
{
    None = 0,
    DAILY_7,
    DAILY_14,
    EVENT_DAILY_7,
}

public enum AttendanceType
{
    None = 0,
    DAILY,
    EVENT_DAILY,
}

public enum ConfigType
{
    None = 0,
    IS_ATTENDANCE_SHEET_DAILY_7_OPEN,
    IS_ATTENDANCE_SHEET_DAILY_14_OPEN,
    IS_ATTENDANCE_SHEET_EVENT_DAILY_7_OPEN,
}

